export const possibleChatStatus = {
    PAYMENT_IN_PROGRESS :'PAYMENT_IN_PROGRESS',
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    CANCELED: 'CANCELED',
    CLOSED: 'CLOSED',
    COMPLETION_IN_PROGRESS:'COMPLETION_IN_PROGRESS',
    COMPLETED:'COMPLETED'
  }