# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'medflic' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for medflic

  target 'medflic-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    #pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
   

  end

  target 'medflicTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
pod 'RNSound', :path => '../node_modules/react-native-sound'
pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'
pod 'ReactNativeIncallManager', :path => '../node_modules/react-native-incall-manager'


platform :ios, '10.0'
pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

 # Flexbox Layout Manager Used By React Native
 pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
 
 pod 'Firebase/Analytics'
 # React Native
 pod 'React', path: '../node_modules/react-native', subspecs: [
   # Comment out any unneeded subspecs to reduce bundle size.
   'Core',
   'DevSupport',
   'RCTActionSheet',
   'RCTAnimation',
   'RCTBlob',
   'RCTCameraRoll',
   'RCTGeolocation',
   'RCTImage',
   'RCTNetwork',
   'RCTPushNotification',
   'RCTSettings',
   'RCTText',
   'RCTVibration',
   'RCTWebSocket',
   'RCTLinkingIOS'
 ]

 # Mapbox
 pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'
 pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
 # Third party
 pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

 post_install do |installer|
   installer.pods_project.targets.each do |target|
      
     targets_to_ignore = %w(React yoga)
     if targets_to_ignore.include? target.name
      target.remove_from_project
     end
     if target.name == "React"
       target.remove_from_project
     end
   end
 end