export const POSSIBLE_VIDEO_CONSULTING_STATUS = {
    PAYMENT_IN_PROGRESS :'PAYMENT_IN_PROGRESS',
    FAILED: 'FAILED',
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    CANCELED: 'CANCELED',
    CLOSED: 'CLOSED'
  }